name: Publish

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pnpm publish
