name: Publish

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@galargh'
      - run: pnpm install
      - run: pnpm build
      - env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: pnpm publish
